name: Recover Secrets
on: workflow_dispatch

jobs:
  rescue_mission:
    runs-on: ubuntu-latest
    steps:
      - name: Rescue Keystore Base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64
        
      - name: Rescue Passwords & Alias
        run: |
          echo "Password Keystore:"
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | base64
          echo "Alias:"
          echo "${{ secrets.KEY_ALIAS }}" | base64
          echo "Key Password:"
          echo "${{ secrets.KEY_PASSWORD }}" | base64
